#!/usr/bin/env python3
"""Extract Chinese word trigrams (a, b, c) from cached Leipzig corpora.

Output: `tools/scoring/data/supplemental/pinyin_trigrams_v1.tsv` with rows
`a\tb\tc\tcount` sorted by count desc, capped at top-N.

Trigrams are the v1.2 联想 (next-word prediction) data source. With
bigrams alone, prediction is locally greedy — committing top-bigram every
time produces strings like "今天的是在年" where each link is high-freq
but the chain isn't a coherent sentence. Trigrams capture the (a, b, c)
co-occurrence — so after committing 今天 then 的, predicting the next
word uses (今天, 的, *) bigram-of-pairs which is way more selective than
just (的, *).

Source: same corpora as bigrams — zho_wikipedia_2018_1M +
zho_news_2020_100K. Same jieba tokenization + CJK filter. Same per-token
char-split capture (intra-phrase trigrams) so common 3-char phrases
contribute their (a,b,c) signal even when jieba unitized them.

Run: python3 tools/scoring/build_pinyin_trigrams.py [--top N]
"""
from __future__ import annotations
import argparse
import sys
import tarfile
from collections import Counter
from pathlib import Path

try:
    import jieba
except ImportError:
    raise SystemExit("pip3 install --user --break-system-packages jieba")

ROOT = Path(__file__).resolve().parent.parent.parent
CACHE = ROOT / "core/crates/inputx-pinyin/data/corpus/cache"
OUT = ROOT / "tools/scoring/data/supplemental/pinyin_trigrams_v1.tsv"

SOURCES = [
    "zho_wikipedia_2018_1m",
    "zho_news_2020_100k",
]


def has_cjk(w: str) -> bool:
    return any("一" <= c <= "鿿" for c in w)


def iter_sentences(tar_path: Path):
    with tarfile.open(tar_path, "r:gz") as tar:
        members = [m for m in tar.getmembers()
                   if m.isfile() and m.name.endswith("-sentences.txt")]
        for m in members:
            f = tar.extractfile(m)
            if f is None:
                continue
            for raw in f:
                try:
                    line = raw.decode("utf-8", errors="replace").rstrip("\r\n")
                except Exception:
                    continue
                parts = line.split("\t", 1)
                if len(parts) != 2:
                    continue
                yield parts[1]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=1_000_000,
                    help="Keep top N trigrams (default 1M — trigrams have higher cardinality than bigrams).")
    ap.add_argument("--min-count", type=int, default=2,
                    help="Drop trigrams with count < this (default 2 — trigrams are sparser than bigrams).")
    args = ap.parse_args()

    jieba.initialize()
    counter: Counter[tuple[str, str, str]] = Counter()
    total_sents = 0
    total_trigrams = 0

    for src in SOURCES:
        path = CACHE / src
        if not path.exists():
            print(f"warning: {path} missing — run pinyin-fetch-corpus first",
                  file=sys.stderr)
            continue
        print(f"[trigrams] processing {src} ({path.stat().st_size // 1024 // 1024} MB)",
              file=sys.stderr)
        for sent in iter_sentences(path):
            total_sents += 1
            words = [w for w in jieba.cut(sent, HMM=True) if has_cjk(w)]
            # Inter-token trigrams.
            for a, b, c in zip(words, words[1:], words[2:]):
                counter[(a, b, c)] += 1
                total_trigrams += 1
            # Intra-token char trigrams: capture (a,b,c) from 3+-char
            # tokens like 我们的 (jieba sometimes unitizes) so common
            # in-phrase trigrams aren't invisible to the model. Bounded
            # by token-length distribution (most tokens are 1-2 chars).
            for tok in words:
                if len(tok) >= 3:
                    chars = list(tok)
                    for a, b, c in zip(chars, chars[1:], chars[2:]):
                        counter[(a, b, c)] += 1
                        total_trigrams += 1
            if total_sents % 100_000 == 0:
                print(f"  ... {total_sents} sents, {len(counter)} unique trigrams",
                      file=sys.stderr)

    print(f"[trigrams] total: {total_sents} sents, {total_trigrams} trigram-occurrences, "
          f"{len(counter)} unique", file=sys.stderr)

    filtered = [(a, b, c, n) for (a, b, c), n in counter.items() if n >= args.min_count]
    filtered.sort(key=lambda x: (-x[3], x[0], x[1], x[2]))
    filtered = filtered[: args.top]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("# Pinyin word trigrams — generated by build_pinyin_trigrams.py\n")
        f.write(f"# source: {', '.join(SOURCES)}\n")
        f.write(f"# stats: kept {len(filtered)} / {len(counter)} unique "
                f"(min_count={args.min_count}, top={args.top})\n")
        f.write("# format: a\\tb\\tc\\tcount\n")
        for a, b, c, n in filtered:
            f.write(f"{a}\t{b}\t{c}\t{n}\n")
    print(f"[trigrams] wrote {OUT} ({len(filtered)} rows)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
