#!/usr/bin/env python3
"""Extract Chinese word-bigram counts from cached Leipzig corpora.

Output: `tools/scoring/data/supplemental/pinyin_bigrams_v1.tsv` with rows
`prev_word\tnext_word\tcount` sorted by count desc, capped at top-N.

The bigram table is consumed by the pinyin engine to rerank candidates
based on the most-recently-committed word. This is the offline analogue
of Sogou's per-user freq adaptation — instead of cloud-trained per-user
freq, we use static cross-corpus bigram counts to capture the "what word
usually follows what" signal.

Architecture rationale:
  - Today (v1.1.x): pinyin candidate score = base + freq. No context.
  - With bigrams: pinyin candidate score = (base + freq) ×
    bigram_boost(last_committed_word, candidate). last_committed empty
    → multiplier = 1.0 (no behavior change for cold sessions).
  - Closes a major UX gap vs Sogou (which makes "今天 → 好" #0 because
    "今天好" is a high-count bigram).

Source: zho_wikipedia_2018_1M (~1M sentences) + zho_news_2020_100K
(~100K sentences). SUBTLEX is freq-list, not raw text, so skipped.

Run: python3 tools/scoring/build_pinyin_bigrams.py [--top N]
"""
from __future__ import annotations
import argparse
import sys
import tarfile
from collections import Counter
from pathlib import Path

try:
    import jieba
except ImportError:
    raise SystemExit("pip3 install --user --break-system-packages jieba")

ROOT = Path(__file__).resolve().parent.parent.parent
CACHE = ROOT / "core/crates/inputx-pinyin/data/corpus/cache"
OUT = ROOT / "tools/scoring/data/supplemental/pinyin_bigrams_v1.tsv"

# Leipzig tarballs contain a directory like `zho_wikipedia_2018_1M/`
# with several files; the one we want is `*-sentences.txt`. Each line:
#   <id>\t<sentence>
SOURCES = [
    "zho_wikipedia_2018_1m",
    "zho_news_2020_100k",
]


def has_cjk(w: str) -> bool:
    return any("一" <= c <= "鿿" for c in w)


def iter_sentences(tar_path: Path):
    """Yield raw sentence strings from a Leipzig tar.gz."""
    with tarfile.open(tar_path, "r:gz") as tar:
        members = [m for m in tar.getmembers()
                   if m.isfile() and m.name.endswith("-sentences.txt")]
        for m in members:
            f = tar.extractfile(m)
            if f is None:
                continue
            for raw in f:
                try:
                    line = raw.decode("utf-8", errors="replace").rstrip("\r\n")
                except Exception:
                    continue
                # `<id>\t<sentence>` — split once, take the tail.
                parts = line.split("\t", 1)
                if len(parts) != 2:
                    continue
                yield parts[1]


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--top", type=int, default=500_000,
                    help="Keep top N bigrams (default 500k).")
    ap.add_argument("--min-count", type=int, default=3,
                    help="Drop bigrams with count < this (default 3).")
    args = ap.parse_args()

    jieba.initialize()
    counter: Counter[tuple[str, str]] = Counter()
    total_sents = 0
    total_bigrams = 0

    for src in SOURCES:
        path = CACHE / src
        if not path.exists():
            print(f"warning: {path} missing — run pinyin-fetch-corpus first",
                  file=sys.stderr)
            continue
        print(f"[bigrams] processing {src} ({path.stat().st_size // 1024 // 1024} MB)",
              file=sys.stderr)
        for sent in iter_sentences(path):
            total_sents += 1
            # jieba segment; filter to CJK-only words (drop English / digits
            # / punctuation tokens — bigrams involving those are noise for
            # a pinyin reranker).
            words = [w for w in jieba.cut(sent, HMM=True) if has_cjk(w)]
            for prev, nxt in zip(words, words[1:]):
                counter[(prev, nxt)] += 1
                total_bigrams += 1
            if total_sents % 100_000 == 0:
                print(f"  ... {total_sents} sents, {len(counter)} unique bigrams",
                      file=sys.stderr)

    print(f"[bigrams] total: {total_sents} sents, {total_bigrams} bigram-occurrences, "
          f"{len(counter)} unique", file=sys.stderr)

    # Filter + sort.
    filtered = [(p, n, c) for (p, n), c in counter.items() if c >= args.min_count]
    filtered.sort(key=lambda x: (-x[2], x[0], x[1]))
    filtered = filtered[: args.top]

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w") as f:
        f.write("# Pinyin word bigrams — generated by build_pinyin_bigrams.py\n")
        f.write(f"# source: {', '.join(SOURCES)}\n")
        f.write(f"# stats: kept {len(filtered)} / {len(counter)} unique "
                f"(min_count={args.min_count}, top={args.top})\n")
        f.write("# format: prev\\tnext\\tcount\n")
        for p, n, c in filtered:
            f.write(f"{p}\t{n}\t{c}\n")
    print(f"[bigrams] wrote {OUT} ({len(filtered)} rows)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
