#!/usr/bin/env python3
"""Generate `core/crates/inputx-nihongo/src/kanji.rs` from
`tools/scoring/data/supplemental/jp_kanji_v1.tsv`.

Input TSV:  kanji<TAB>readings<TAB>freq
Output:     a Rust source file with KanjiEntry { ch, readings, freq } table.

Dedup rules:
  - one row per kanji char (first wins)
  - readings normalized (lowercase, dedup within list)
  - drop rows where kanji isn't a CJK ideograph
  - drop rows whose readings contain non-ASCII or empty after split
"""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
TSV = ROOT / "tools/scoring/data/supplemental/jp_kanji_v1.tsv"
OUT = ROOT / "core/crates/inputx-nihongo/src/kanji.rs"


def is_cjk(c: str) -> bool:
    return any(start <= ord(c) <= end for start, end in [
        (0x3400, 0x4DBF),
        (0x4E00, 0x9FFF),
        (0x20000, 0x2A6DF),
        (0xF900, 0xFAFF),
    ])


def main() -> int:
    seen: set[str] = set()
    rows: list[tuple[str, list[str], int]] = []
    skipped = 0
    with TSV.open() as f:
        for line in f:
            line = line.rstrip("\n").strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            if len(parts) != 3:
                skipped += 1
                continue
            ch_s, readings_s, freq_s = parts
            if len(ch_s) != 1 or not is_cjk(ch_s):
                skipped += 1
                continue
            if ch_s in seen:
                continue
            try:
                freq = int(freq_s)
            except ValueError:
                skipped += 1
                continue
            readings = []
            for r in readings_s.split(","):
                r = r.strip().lower()
                if not r or not all(c.isascii() and c.isalpha() for c in r):
                    continue
                if r not in readings:
                    readings.append(r)
            if not readings:
                skipped += 1
                continue
            seen.add(ch_s)
            rows.append((ch_s, readings, freq))

    rows.sort(key=lambda r: (-r[2], r[0]))
    print(f"kept {len(rows)} rows, skipped {skipped}", file=sys.stderr)

    out = []
    out.append("//! Kanji table — JP kanji with on/kun readings + relative frequency.\n")
    out.append("//!\n")
    out.append("//! Generated by `tools/jp/build_kanji_rs.py` from\n")
    out.append("//! `tools/scoring/data/supplemental/jp_kanji_v1.tsv`. DO NOT edit by hand —\n")
    out.append("//! re-run the script. The source TSV was produced by an LLM batch call;\n")
    out.append("//! corrections go to the TSV first, then regenerate.\n")
    out.append("//!\n")
    out.append("//! Schema: each kanji carries 1+ Hepburn romaji readings (on-yomi + kun-yomi\n")
    out.append("//! stems where the bare-kanji is the natural surface form) and a 0–100 freq\n")
    out.append("//! score. Composite-layer scoring uses `freq` to lift high-frequency JP\n")
    out.append("//! kanji above rare Chinese chars / 生僻词组 per the user's design rule\n")
    out.append("//! (2026-05-23: '日语高频要高于中文难检字和生僻词组').\n")
    out.append("//!\n")
    out.append("//! Codepoint-identity-with-SC constraint REMOVED (was the v1.1 design).\n")
    out.append("//! Shinjitai-only kanji (経/漢/楽/愛/東/見/書/…) are first-class entries\n")
    out.append("//! now — Inputx's JP plugin delivers professional-grade JP, not just\n")
    out.append("//! the SC-overlap subset.\n")
    out.append("\n")
    out.append("#[derive(Copy, Clone, Debug)]\n")
    out.append("pub struct KanjiEntry {\n")
    out.append("    pub kanji: char,\n")
    out.append("    pub readings: &'static [&'static str],\n")
    out.append("    pub freq: u32,\n")
    out.append("}\n")
    out.append("\n")
    out.append("const fn k(c: char, r: &'static [&'static str], f: u32) -> KanjiEntry {\n")
    out.append("    KanjiEntry { kanji: c, readings: r, freq: f }\n")
    out.append("}\n")
    out.append("\n")
    out.append("/// Lookup: given a Hepburn romaji string, return all (kanji, freq) tuples\n")
    out.append("/// whose readings include exactly that string. Linear scan over the table\n")
    out.append("/// is fine for a few thousand entries — modern keystroke-rate cost is\n")
    out.append("/// dominated by the FST traversal in the wubi/pinyin engines, not this.\n")
    out.append("pub fn lookup_by_reading(romaji: &str) -> impl Iterator<Item = (char, u32)> + '_ {\n")
    out.append("    KANJI_TABLE.iter().filter_map(move |e| {\n")
    out.append("        if e.readings.iter().any(|r| *r == romaji) {\n")
    out.append("            Some((e.kanji, e.freq))\n")
    out.append("        } else {\n")
    out.append("            None\n")
    out.append("        }\n")
    out.append("    })\n")
    out.append("}\n")
    out.append("\n")
    out.append("#[rustfmt::skip]\n")
    out.append(f"pub const KANJI_TABLE: &[KanjiEntry] = &[\n")
    for ch, readings, freq in rows:
        r_lits = ", ".join(f'"{r}"' for r in readings)
        out.append(f"    k('{ch}', &[{r_lits}], {freq}),\n")
    out.append("];\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT} ({len(rows)} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
