#!/usr/bin/env python3
"""Generate `core/crates/inputx-jp/src/jukugo.rs` from the supplemental TSV."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent.parent
SUPP_DIR = ROOT / "tools/scoring/data/supplemental"
# Source TSVs (deterministic order: jukugo first so it wins identity ties at
# parity, counters/extras layered on top via highest-freq selection below).
SOURCES = [
    SUPP_DIR / "jp_jukugo_v1.tsv",
    SUPP_DIR / "jp_counters_v1.tsv",
]
OUT = ROOT / "core/crates/inputx-jp/src/jukugo.rs"


def main() -> int:
    # Key on (reading, word). When the same pair appears in multiple TSVs we
    # keep the highest freq — lets counter file be regenerated independently
    # without worrying about freq regressions from low-baseline rows.
    best: dict[tuple[str, str], int] = {}
    skipped = 0
    for tsv in SOURCES:
        if not tsv.exists():
            print(f"warning: source missing: {tsv}", file=sys.stderr)
            continue
        with tsv.open() as f:
            for line in f:
                line = line.rstrip("\n").strip()
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) != 3:
                    skipped += 1
                    continue
                word, reading, freq_s = parts
                word = word.strip()
                reading = reading.strip().lower()
                if not word or not reading:
                    skipped += 1
                    continue
                if not all(c.isascii() and c.isalpha() for c in reading):
                    skipped += 1
                    continue
                try:
                    freq = int(freq_s)
                except ValueError:
                    skipped += 1
                    continue
                key = (reading, word)
                cur = best.get(key)
                if cur is None or freq > cur:
                    best[key] = freq
    rows = [(reading, word, freq) for (reading, word), freq in best.items()]
    rows.sort(key=lambda r: (-r[2], r[0], r[1]))
    print(f"kept {len(rows)} rows, skipped {skipped}", file=sys.stderr)

    out = []
    out.append("//! Jukugo (熟語) table — JP compound words with reading + freq.\n")
    out.append("//!\n")
    out.append("//! Generated by `tools/jp/build_jukugo_rs.py` from the supplemental TSV.\n")
    out.append("//! DO NOT edit by hand — re-run the script. Corrections go to the TSV.\n")
    out.append("//!\n")
    out.append("//! Codepoint-identity-with-SC constraint REMOVED — Inputx's JP plugin is\n")
    out.append("//! professional-grade now, so shinjitai-only compounds (経済/愛情/電話/…)\n")
    out.append("//! are first-class.\n")
    out.append("\n")
    out.append("#[derive(Copy, Clone, Debug)]\n")
    out.append("pub struct JukugoEntry {\n")
    out.append("    pub reading: &'static str,\n")
    out.append("    pub kanji: &'static str,\n")
    out.append("    pub freq: u32,\n")
    out.append("}\n")
    out.append("\n")
    out.append("const fn j(r: &'static str, k: &'static str, f: u32) -> JukugoEntry {\n")
    out.append("    JukugoEntry { reading: r, kanji: k, freq: f }\n")
    out.append("}\n")
    out.append("\n")
    out.append("pub fn lookup_by_reading(romaji: &str) -> impl Iterator<Item = (&'static str, u32)> + '_ {\n")
    out.append("    JUKUGO_TABLE.iter().filter_map(move |e| {\n")
    out.append("        if e.reading == romaji { Some((e.kanji, e.freq)) } else { None }\n")
    out.append("    })\n")
    out.append("}\n")
    out.append("\n")
    out.append("#[rustfmt::skip]\n")
    out.append(f"pub const JUKUGO_TABLE: &[JukugoEntry] = &[\n")
    for reading, word, freq in rows:
        out.append(f'    j("{reading}", "{word}", {freq}),\n')
    out.append("];\n")

    OUT.write_text("".join(out))
    print(f"wrote {OUT} ({len(rows)} entries)", file=sys.stderr)
    return 0


if __name__ == "__main__":
    sys.exit(main())
