#!/usr/bin/env python3
"""03_normalize — reproduce build_weights' sum-then-log normalization (CP2).

CP2 of the dict-pipeline rebuild aligns the designed pipeline against the
*bare* `build_weights` output (the L4-locked identity target). build_weights
normalizes with a **cross-source sum-then-log**, NOT the per-source log-rank
that SCORING.md §03 ultimately calls for — and per-source log-rank cannot
byte-identically reproduce sum-then-log. So CP2 reproduces sum-then-log here
to establish the identity baseline; per-source log-rank is a deliberate CP3+
evolution (diff-reviewable). See .claude/PLAN-dict-pipeline.md (CP2 hot plan).

Because build_weights couples normalization with the cross-source merge (it
must sum across sources before it can take the log), this step temporarily
absorbs what SCORING.md assigns to 05_merge — it reads the per-source
unweighted counts from 02_extract and emits the final merged weights.tsv
directly. CP3+ will split per-source normalize (03) from cross-source
weighted average (05).

Inputs:
  tools/scoring/data/extracted/<src>/freq.tsv   (02_extract: word\\tcount, unweighted)
  core/crates/inputx-pinyin/data/readings.tsv   (word -> [pinyin] enumeration)
  core/crates/inputx-pinyin/data/corpus/manifest.toml  (per-source weight)
  core/crates/inputx-pinyin/tools/weights/rules.toml   (min_count, max_freq_score)

Output:
  tools/scoring/data/merged/weights.tsv

Identity gate (CP2):
  diff tools/scoring/data/baseline/weights-bare.tsv \\
       tools/scoring/data/merged/weights.tsv   # must be byte-identical

Reproduction fidelity — three Rust->Python traps handled here:
  1. Rust f64::round() is round-half-away-from-zero; Python's round() is
     banker's rounding, and floor(x+0.5) mis-rounds near 0.4999..994. We use
     a floor()+diff form that matches round-half-away exactly for x >= 0.
  2. math.log == Rust f64::ln on the same machine (both link macOS libm), so
     ln(1+raw) is expected bit-identical. Any residual diff would be a single
     round-boundary +-1, surfaced by the identity gate for manual review.
  3. Aho-Corasick overlapping counting is NOT redone here — 02_extract reuses
     build_weights' deterministic Rust counter, so this step only reproduces
     the arithmetic (sum -> ln -> min-max -> round), not the counting.
"""

from __future__ import annotations

import math
import subprocess
import sys
import tomllib
from pathlib import Path

PINYIN_DATA = "core/crates/inputx-pinyin/data"
MANIFEST_REL = f"{PINYIN_DATA}/corpus/manifest.toml"
RULES_REL = "core/crates/inputx-pinyin/tools/weights/rules.toml"
READINGS_REL = f"{PINYIN_DATA}/readings.tsv"

# Mirrors render_weights_tsv in build_weights.rs exactly (em-dash is U+2014).
# merged/weights.tsv must be byte-identical to baseline/weights-bare.tsv,
# which build_weights' dump writes via render_weights_tsv — so the header text
# is dictated by that function, not by this step's actual provenance.
HEADER = (
    "# pinyin\tword\tfreq_score\n"
    "# generated by pinyin-build-weights — DO NOT EDIT BY HAND. Regenerate via:\n"
    "#   cargo run --features tools --release --bin pinyin-build-weights\n"
)


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True,
        text=True,
        check=True,
    )
    return Path(out.stdout.strip())


def round_half_away(x: float) -> int:
    """round-half-away-from-zero for x >= 0, matching Rust f64::round().

    Avoids floor(x + 0.5)'s cross-boundary bug at x = 0.49999999999999994 by
    flooring first and comparing the fractional part to 0.5.
    """
    f = math.floor(x)
    diff = x - f
    if diff < 0.5:
        return f
    return f + 1  # diff >= 0.5: round away from zero (x >= 0)


def load_per_source_raw(
    extracted_dir: Path, weights: dict[str, float]
) -> dict[str, float]:
    """Cross-source weighted sum: raw[word] = sum_src count(src,word) * weight(src).

    Integer-valued f64 terms make the sum order-independent, matching the
    accum build_weights' dump rebuilds. Sources sorted for determinism.
    """
    raw: dict[str, float] = {}
    for src in sorted(weights):
        weight = weights[src]
        freq_path = extracted_dir / src / "freq.tsv"
        if not freq_path.exists():
            sys.exit(
                f"error: missing 02_extract output {freq_path} — run `make 02-extract` first"
            )
        with open(freq_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.rstrip("\r\n")
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) < 2:
                    continue
                word, count_s = parts[0], parts[1]
                try:
                    count = int(count_s)
                except ValueError:
                    continue
                raw[word] = raw.get(word, 0.0) + count * weight
    return raw


def enumerate_entries(readings_path: Path) -> list[tuple[str, str]]:
    """(pinyin, word) pairs — mirrors enumerate_entries in build_weights.rs."""
    entries: list[tuple[str, str]] = []
    with open(readings_path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.rstrip("\r\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            word = parts[0]
            if not word:
                continue
            for pinyin in parts[1:]:
                pinyin = pinyin.strip()
                if not pinyin:
                    continue
                entries.append((pinyin, word))
    return entries


def main() -> int:
    root = repo_root()
    extracted_dir = root / "tools/scoring/data/extracted"
    out_path = root / "tools/scoring/data/merged/weights.tsv"

    with open(root / MANIFEST_REL, "rb") as fh:
        manifest = tomllib.load(fh)
    weights = {src: spec["weight"] for src, spec in manifest.get("corpus", {}).items()}
    if not weights:
        sys.exit("error: manifest.toml has no [corpus.*] entries")

    with open(root / RULES_REL, "rb") as fh:
        rules = tomllib.load(fh)
    norm = rules["normalization"]
    min_count = float(norm["min_count"])
    cap = float(norm["max_freq_score"])

    raw = load_per_source_raw(extracted_dir, weights)
    entries = enumerate_entries(root / READINGS_REL)

    # Global log + min-max, per-entry (same word across readings shares raw,
    # hence shares freq_score) — mirrors normalize_global in build_weights.rs.
    log_counts = [0.0] * len(entries)
    max_lc = 0.0
    for i, (_pinyin, word) in enumerate(entries):
        r = raw.get(word, 0.0)
        lc = 0.0 if r < min_count else math.log(1.0 + r)
        log_counts[i] = lc
        if lc > max_lc:
            max_lc = lc

    rows: list[tuple[str, str, int]] = []
    for i, (pinyin, word) in enumerate(entries):
        freq = round_half_away(log_counts[i] / max_lc * cap) if max_lc > 0.0 else 0
        rows.append((pinyin, word, freq))

    # Byte-order sort to match Rust String::cmp (UTF-8 is order-preserving, so
    # this equals code-point order, but encoding is unambiguous).
    rows.sort(key=lambda r: (r[0].encode("utf-8"), r[1].encode("utf-8")))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="") as fh:
        fh.write(HEADER)
        fh.writelines(f"{pinyin}\t{word}\t{freq}\n" for pinyin, word, freq in rows)

    print(f"wrote {out_path} ({len(rows)} rows, max_lc={max_lc:.10f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
