#!/usr/bin/env python3
"""03_normalize — turn per-source counts into a unified weights.tsv.

Three modes (--mode):

  per-source-log-count  (default, CP3b — chosen 2026-05-25) — SCORING.md §03's
      per-source scale-free normalization, but keeping count magnitude:
      score[word] = Σ_src α[src] × ln(1+count)/max_ln[src], α = manifest.weight;
      global min-max → freq_score. Chosen over the literal rank-based log-rank
      after gate1/coverage data: rank collapses the long tail (dict 22k vs
      219k kept) while log-count keeps full coverage AND improves gate1
      (kaopu→靠谱 to #1).

  per-source-log-rank  (SCORING.md §03 literal) — within each source, dense-rank
      words by count, score 1 - ln(rank)/ln(N+1). Scale-free, but on our
      homogeneous occurrence-count sources it discards count magnitude → the
      long tail's freq_score trends to 0 and is cut by build_dict's MIN_FREQ
      (coverage 22k/219k). Kept for reference / future heterogeneous sources.

  sum-then-log  (CP2 identity baseline) — reproduce build_weights' cross-source
      sum-then-log byte-identically. raw[word]=Σ_src count×weight; per-entry
      lc=ln(1+raw) (0 if raw<min_count); global min-max. `make identity-check`
      validates the counting chain still reproduces build_weights bit-for-bit.

Because build_weights couples normalize with the cross-source merge (it sums
across sources before taking the log), sum-then-log emits merged/weights.tsv
directly; per-source-log-rank does the per-source rank here then the weighted
merge in the same pass (CP3's 03+05 are fused until they need splitting).

Inputs:  tools/scoring/data/extracted/<src>/freq.tsv (02_extract),
         readings.tsv, corpus/manifest.toml (weights), rules.toml.
Output:  tools/scoring/data/merged/weights.tsv

Rust→Python fidelity (sum-then-log identity): round-half-away (not banker's),
libm ln, byte-order sort — see CP2 notes.
"""

from __future__ import annotations

import argparse
import math
import subprocess
import sys
import tomllib
from pathlib import Path

PINYIN_DATA = "core/crates/inputx-pinyin/data"
MANIFEST_REL = f"{PINYIN_DATA}/corpus/manifest.toml"
RULES_REL = "core/crates/inputx-pinyin/tools/weights/rules.toml"
READINGS_REL = f"{PINYIN_DATA}/readings.tsv"

# Mirrors render_weights_tsv in build_weights.rs exactly (em-dash is U+2014).
HEADER = (
    "# pinyin\tword\tfreq_score\n"
    "# generated by pinyin-build-weights — DO NOT EDIT BY HAND. Regenerate via:\n"
    "#   cargo run --features tools --release --bin pinyin-build-weights\n"
)


def repo_root() -> Path:
    out = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        capture_output=True, text=True, check=True,
    )
    return Path(out.stdout.strip())


def round_half_away(x: float) -> int:
    """round-half-away-from-zero for x >= 0 (Rust f64::round); avoids the
    floor(x+0.5) cross-boundary bug at x=0.49999999999999994."""
    f = math.floor(x)
    return f if (x - f) < 0.5 else f + 1


def load_per_source_counts(
    extracted_dir: Path, srcs: list[str]
) -> dict[str, dict[str, int]]:
    """{src: {word: count}} from 02_extract freq.tsv files (sorted srcs)."""
    out: dict[str, dict[str, int]] = {}
    for src in srcs:
        freq_path = extracted_dir / src / "freq.tsv"
        if not freq_path.exists():
            sys.exit(f"error: missing 02_extract output {freq_path} — run `make 02-extract` first")
        counts: dict[str, int] = {}
        with open(freq_path, encoding="utf-8") as fh:
            for line in fh:
                line = line.rstrip("\r\n")
                if not line or line.startswith("#"):
                    continue
                parts = line.split("\t")
                if len(parts) < 2:
                    continue
                try:
                    counts[parts[0]] = counts.get(parts[0], 0) + int(parts[1])
                except ValueError:
                    continue
        out[src] = counts
    return out


def score_sum_then_log(
    per_source: dict[str, dict[str, int]], weights: dict[str, float], min_count: float
) -> dict[str, float]:
    """word → ln(1+Σ count×weight) (0 if raw<min_count). Integer-valued f64
    sums are order-independent → matches build_weights' accum bit-for-bit."""
    raw: dict[str, float] = {}
    for src in sorted(weights):
        w = weights[src]
        for word, c in per_source[src].items():
            raw[word] = raw.get(word, 0.0) + c * w
    return {
        word: (math.log(1.0 + r) if r >= min_count else 0.0)
        for word, r in raw.items()
    }


def score_per_source_log_rank(
    per_source: dict[str, dict[str, int]], weights: dict[str, float]
) -> dict[str, float]:
    """word → Σ_src α[src] × (1 - ln(rank)/ln(N+1)), dense-rank by count desc."""
    score: dict[str, float] = {}
    for src in sorted(weights):
        alpha = weights[src]
        counts = per_source[src]
        if not counts:
            continue
        distinct = sorted(set(counts.values()), reverse=True)
        count_to_rank = {c: i + 1 for i, c in enumerate(distinct)}
        denom = math.log(len(distinct) + 1)
        if denom <= 0.0:
            continue
        for word, c in counts.items():
            lr = 1.0 - math.log(count_to_rank[c]) / denom
            score[word] = score.get(word, 0.0) + alpha * lr
    return score


def score_per_source_log_count(
    per_source: dict[str, dict[str, int]], weights: dict[str, float]
) -> dict[str, float]:
    """word → Σ_src α[src] × ln(1+count)/max_ln[src] — per-source log-count
    min-max. Scale-free across sources (like log-rank) but KEEPS count
    magnitude (unlike rank), so the long tail doesn't collapse toward 0 and
    get cut by build_dict's MIN_FREQ. A middle ground between sum-then-log
    (global, subtlex-dominated) and per-source-log-rank (rank, tail-collapsing).
    """
    score: dict[str, float] = {}
    for src in sorted(weights):
        alpha = weights[src]
        counts = per_source[src]
        if not counts:
            continue
        max_ln = max(math.log(1.0 + c) for c in counts.values())
        if max_ln <= 0.0:
            continue
        for word, c in counts.items():
            score[word] = score.get(word, 0.0) + alpha * math.log(1.0 + c) / max_ln
    return score


def enumerate_entries(readings_path: Path) -> list[tuple[str, str]]:
    """(pinyin, word) pairs — mirrors enumerate_entries in build_weights.rs."""
    entries: list[tuple[str, str]] = []
    with open(readings_path, encoding="utf-8") as fh:
        for raw in fh:
            line = raw.rstrip("\r\n")
            if not line or line.startswith("#"):
                continue
            parts = line.split("\t")
            word = parts[0]
            if not word:
                continue
            for pinyin in parts[1:]:
                pinyin = pinyin.strip()
                if pinyin:
                    entries.append((pinyin, word))
    return entries


def main() -> int:
    ap = argparse.ArgumentParser(description="03_normalize — counts → weights.tsv")
    ap.add_argument(
        "--mode",
        choices=["sum-then-log", "per-source-log-rank", "per-source-log-count"],
        default="per-source-log-count",
        help="normalization algorithm (default per-source-log-count = CP3b; "
        "sum-then-log reproduces the CP2 identity baseline)",
    )
    ap.add_argument(
        "--out",
        default=None,
        help="output path (default tools/scoring/data/merged/weights.tsv)",
    )
    args = ap.parse_args()

    root = repo_root()
    extracted_dir = root / "tools/scoring/data/extracted"
    out_path = Path(args.out) if args.out else root / "tools/scoring/data/merged/weights.tsv"

    with open(root / MANIFEST_REL, "rb") as fh:
        manifest = tomllib.load(fh)
    weights = {src: spec["weight"] for src, spec in manifest.get("corpus", {}).items()}
    if not weights:
        sys.exit("error: manifest.toml has no [corpus.*] entries")
    with open(root / RULES_REL, "rb") as fh:
        norm = tomllib.load(fh)["normalization"]
    min_count = float(norm["min_count"])
    cap = float(norm["max_freq_score"])

    per_source = load_per_source_counts(extracted_dir, sorted(weights))
    if args.mode == "sum-then-log":
        word_score = score_sum_then_log(per_source, weights, min_count)
    elif args.mode == "per-source-log-rank":
        word_score = score_per_source_log_rank(per_source, weights)
    else:
        word_score = score_per_source_log_count(per_source, weights)

    entries = enumerate_entries(root / READINGS_REL)

    # Per-entry pre-minmax score (same word across readings shares it), then
    # global min-max → freq_score. Mirrors normalize_global in build_weights.rs.
    vals = [word_score.get(word, 0.0) for _p, word in entries]
    max_v = max(vals) if vals else 0.0

    rows = [
        (pinyin, word, round_half_away(v / max_v * cap) if max_v > 0.0 else 0)
        for (pinyin, word), v in zip(entries, vals)
    ]
    rows.sort(key=lambda r: (r[0].encode("utf-8"), r[1].encode("utf-8")))

    out_path.parent.mkdir(parents=True, exist_ok=True)
    with open(out_path, "w", encoding="utf-8", newline="") as fh:
        fh.write(HEADER)
        fh.writelines(f"{p}\t{w}\t{f}\n" for p, w, f in rows)

    print(f"wrote {out_path} ({len(rows)} rows, mode={args.mode}, max_score={max_v:.10f})")
    return 0


if __name__ == "__main__":
    sys.exit(main())
