//! `pinyin-build-trigrams-fst` — pack the word-trigram TSV into a
//! mmap-loadable FST consumed by the pinyin engine for context-aware
//! next-word prediction (联想 v1.2 — sentence-level coherence).
//!
//! Input:  `tools/scoring/data/supplemental/pinyin_trigrams_v1.tsv`
//!         (generated by `tools/scoring/build_pinyin_trigrams.py`)
//! Output: `core/crates/inputx-pinyin/data/trigrams.fst`
//!
//! Key format: `<a>\0<b>\0<c>` (a / b / c are UTF-8 word strings).
//! Range-scanning `[a\0b\0, a\0b\1)` enumerates every trigram starting
//! with the (a, b) prefix — that's how `predict_next_words_context`
//! finds candidate `c` words given the user's last two committed words.
//!
//! Re-run any time the TSV changes:
//!     cargo run --features tools --release --bin pinyin-build-trigrams-fst

use fst::MapBuilder;
use std::fs;
use std::io::BufWriter;
use std::path::PathBuf;

fn main() {
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let tsv_path = crate_dir
        .parent().expect("crates parent")
        .parent().expect("workspace root")
        .join("../tools/scoring/data/supplemental/pinyin_trigrams_v1.tsv");
    let fst_path = crate_dir.join("data/trigrams.fst");

    let tsv = fs::read_to_string(&tsv_path).unwrap_or_else(|_| {
        panic!(
            "{} missing — run `python3 tools/scoring/build_pinyin_trigrams.py` first",
            tsv_path.display()
        )
    });

    // schema: <a>\t<b>\t<c>\t<count>
    let mut entries: Vec<(Vec<u8>, u64)> = Vec::with_capacity(1_000_000);
    let mut malformed = 0usize;
    for raw in tsv.lines() {
        let line = raw.trim_end_matches(['\r', '\n']);
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.split('\t');
        let a = parts.next().unwrap_or("").trim();
        let b = parts.next().unwrap_or("").trim();
        let c = parts.next().unwrap_or("").trim();
        let count: u64 = parts
            .next()
            .and_then(|s| s.trim().parse().ok())
            .unwrap_or(0);
        if a.is_empty() || b.is_empty() || c.is_empty() || count == 0 {
            malformed += 1;
            continue;
        }
        let mut key = a.as_bytes().to_vec();
        key.push(0u8);
        key.extend_from_slice(b.as_bytes());
        key.push(0u8);
        key.extend_from_slice(c.as_bytes());
        entries.push((key, count));
    }
    entries.sort();
    entries.dedup_by(|a, b| a.0 == b.0);

    let writer = BufWriter::new(
        fs::File::create(&fst_path).expect("create trigrams.fst"),
    );
    let mut builder = MapBuilder::new(writer).expect("MapBuilder::new");
    for (key, value) in &entries {
        builder.insert(key, *value).expect("insert");
    }
    builder.finish().expect("MapBuilder::finish");

    eprintln!(
        "trigrams.fst: {} entries, {} malformed, {} bytes",
        entries.len(),
        malformed,
        fs::metadata(&fst_path).map(|m| m.len()).unwrap_or(0),
    );
}
