//! `pinyin-build-fst` — pre-build `data/pinyin.fst` from
//! `data/weights/weights.tsv` (the output of `pinyin-build-weights`).
//!
//! The committed `data/pinyin.fst` is what the published crate ships;
//! consumers don't need `weights.tsv` (or any of the intermediate
//! generation files), keeping the published crate under crates.io's size
//! cap. Maintainers re-run this any time `weights.tsv` changes:
//!
//!     cargo run --features tools --release --bin pinyin-build-fst
//!
//! Then commit `data/pinyin.fst`. CI's `weights-verify` job already
//! catches drift between `weights.tsv` and its inputs; this script's
//! output is downstream of that gate.

use std::env;
use std::fs;
use std::io::BufWriter;
use std::path::PathBuf;

fn main() {
    let crate_dir = PathBuf::from(env::var("CARGO_MANIFEST_DIR").unwrap());
    let weights_path = crate_dir.join("data/weights/weights.tsv");
    let fst_path = crate_dir.join("data/pinyin.fst");

    let tsv = fs::read_to_string(&weights_path).unwrap_or_else(|_| {
        panic!(
            "{} missing — run pinyin-build-weights first (item 21)",
            weights_path.display()
        )
    });

    // Frequency floor for the deployed FST. weights.tsv is kept whole
    // (source of truth for future re-scoring), but only entries above
    // this cutoff get packed into pinyin.fst — drops the long-tail
    // Wikipedia/Leipzig trash that real users never type but that
    // crowds candidate panels with noise. Empirically 47% of weights
    // sit below freq=100 with no observed pick rate. Tune via env var
    // for experimentation (`PINYIN_FST_MIN_FREQ=50 cargo run ...`).
    let min_freq: u64 = std::env::var("PINYIN_FST_MIN_FREQ")
        .ok()
        .and_then(|v| v.parse().ok())
        .unwrap_or(100);

    // weights.tsv schema: `<pinyin>\t<word>\t<freq_score>`. Multiple rows
    // per (pinyin, word) shouldn't exist by construction, but dedup
    // defensively (FST::insert requires sorted unique keys).
    let mut entries: Vec<(Vec<u8>, u64)> = Vec::with_capacity(1_000_000);
    let mut total_seen = 0usize;
    let mut dropped_low = 0usize;
    for raw in tsv.lines() {
        let line = raw.trim_end_matches(['\r', '\n']);
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.split('\t');
        let pinyin = parts.next().unwrap_or("").trim();
        let word = parts.next().unwrap_or("").trim();
        let freq: u64 = parts
            .next()
            .and_then(|s| s.trim().parse().ok())
            .unwrap_or(0);
        if pinyin.is_empty() || word.is_empty() {
            continue;
        }
        total_seen += 1;
        if freq < min_freq {
            dropped_low += 1;
            continue;
        }
        let mut key = pinyin.as_bytes().to_vec();
        key.push(0u8);
        key.extend_from_slice(word.as_bytes());
        entries.push((key, freq));
    }
    entries.sort();
    entries.dedup_by(|a, b| a.0 == b.0);
    eprintln!(
        "freq cutoff: min={} kept={} dropped={} (of {})",
        min_freq, entries.len(), dropped_low, total_seen
    );

    // Overlay sources. Both apply on top of the freq-cutoff'd entries
    // by upsert (key exists → overwrite freq; new key → insert).
    //   1. polish_reports/quickfix_boost.tsv — generated by
    //      `aggregate_polish_log.py` from real user picks. Offline-IME
    //      equivalent of Sogou's behavior-driven cloud freq tuning.
    //   2. supplemental/pinyin_modern_v1.tsv — hand-curated modern
    //      vocab (IT/SNS/workplace/finance/slang) that primary corpora
    //      (Wikipedia/Leipzig) under-represent. Layer 1 of the polish
    //      plan — pure word-addition + freq-boost.
    let supplemental_dir = crate_dir
        .parent().expect("crates parent")
        .parent().expect("workspace root")
        .join("../tools/scoring/data");
    let overlays: &[(&str, std::path::PathBuf)] = &[
        ("polish-log",   supplemental_dir.join("polish_reports/quickfix_boost.tsv")),
        ("modern-vocab", supplemental_dir.join("supplemental/pinyin_modern_v1.tsv")),
    ];

    let mut by_key: std::collections::HashMap<Vec<u8>, u64> =
        entries.iter().cloned().collect();
    for (label, path) in overlays {
        let Ok(text) = fs::read_to_string(path) else {
            eprintln!("overlay {}: SKIPPED (no {})", label, path.display());
            continue;
        };
        let mut applied = 0usize;
        for raw in text.lines() {
            let line = raw.trim_end_matches(['\r', '\n']);
            if line.is_empty() || line.starts_with('#') {
                continue;
            }
            let mut parts = line.split('\t');
            let pinyin = parts.next().unwrap_or("").trim();
            let word = parts.next().unwrap_or("").trim();
            let freq_s = parts.next().unwrap_or("").trim();
            // freq may have a trailing "# n=N" comment (polish-log style)
            let freq_clean = freq_s.split('#').next().unwrap_or("").trim();
            let Ok(freq) = freq_clean.parse::<u64>() else { continue };
            if pinyin.is_empty() || word.is_empty() { continue; }
            let mut key = pinyin.as_bytes().to_vec();
            key.push(0u8);
            key.extend_from_slice(word.as_bytes());
            by_key.insert(key, freq);
            applied += 1;
        }
        eprintln!("overlay {}: applied {} entries from {}", label, applied, path.display());
    }
    entries = by_key.into_iter().collect();
    entries.sort();
    entries.dedup_by(|a, b| a.0 == b.0);

    let writer = BufWriter::new(fs::File::create(&fst_path).expect("create pinyin.fst"));
    let mut builder = fst::MapBuilder::new(writer).expect("MapBuilder::new");
    for (key, value) in &entries {
        builder.insert(key, *value).expect("insert");
    }
    builder.finish().expect("MapBuilder::finish");

    eprintln!(
        "wrote {} entries to {} ({} bytes)",
        entries.len(),
        fst_path.display(),
        fs::metadata(&fst_path).map(|m| m.len()).unwrap_or(0),
    );
}
