//! `pinyin-build-bigrams-fst` — pack the word-bigram TSV into a
//! mmap-loadable FST consumed by the pinyin engine for context-aware
//! candidate reranking.
//!
//! Input:  `tools/scoring/data/supplemental/pinyin_bigrams_v1.tsv`
//!         (generated by `tools/scoring/build_pinyin_bigrams.py`)
//! Output: `core/crates/inputx-pinyin/data/bigrams.fst`
//!
//! Key format mirrors pinyin.fst's compound-key trick: the prev word
//! and next word are joined by a single `\0` byte. Value is the raw
//! count (u64); the runtime applies log-scaling.
//!
//! Re-run any time the TSV changes:
//!     cargo run --features tools --release --bin pinyin-build-bigrams-fst

use fst::MapBuilder;
use std::fs;
use std::io::BufWriter;
use std::path::PathBuf;

fn main() {
    let crate_dir = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let tsv_path = crate_dir
        .parent().expect("crates parent")
        .parent().expect("workspace root")
        .join("../tools/scoring/data/supplemental/pinyin_bigrams_v1.tsv");
    let fst_path = crate_dir.join("data/bigrams.fst");

    let tsv = fs::read_to_string(&tsv_path).unwrap_or_else(|_| {
        panic!(
            "{} missing — run `python3 tools/scoring/build_pinyin_bigrams.py` first",
            tsv_path.display()
        )
    });

    // schema: <prev>\t<next>\t<count>
    let mut entries: Vec<(Vec<u8>, u64)> = Vec::with_capacity(1_000_000);
    let mut malformed = 0usize;
    for raw in tsv.lines() {
        let line = raw.trim_end_matches(['\r', '\n']);
        if line.is_empty() || line.starts_with('#') {
            continue;
        }
        let mut parts = line.split('\t');
        let prev = parts.next().unwrap_or("").trim();
        let nxt = parts.next().unwrap_or("").trim();
        let count: u64 = parts
            .next()
            .and_then(|s| s.trim().parse().ok())
            .unwrap_or(0);
        if prev.is_empty() || nxt.is_empty() || count == 0 {
            malformed += 1;
            continue;
        }
        let mut key = prev.as_bytes().to_vec();
        key.push(0u8);
        key.extend_from_slice(nxt.as_bytes());
        entries.push((key, count));
    }
    entries.sort();
    entries.dedup_by(|a, b| a.0 == b.0);

    let writer = BufWriter::new(
        fs::File::create(&fst_path).expect("create bigrams.fst"),
    );
    let mut builder = MapBuilder::new(writer).expect("MapBuilder::new");
    for (key, value) in &entries {
        builder.insert(key, *value).expect("insert");
    }
    builder.finish().expect("MapBuilder::finish");

    eprintln!(
        "bigrams.fst: {} entries, {} malformed, {} bytes",
        entries.len(),
        malformed,
        fs::metadata(&fst_path).map(|m| m.len()).unwrap_or(0),
    );
}
