#!/usr/bin/env python3
"""build-modern-freq.py — generate modern_freq.tsv for v2 ranking tiebreaker.

Reads:
  - jieba dict.txt (modern Chinese word frequencies)
  - v2 words.tsv (all v2 words; we only score what's already in our dict)
  - v2 chars.tsv (all v2 chars; same)

Writes:
  - core/crates/inputx-pinyin-v2/data/modern_freq.tsv
    Format: <word_or_char>\t<score>
    Score: round(percentile_rank * 25000), 0 for words not in jieba.

Design rationale: see docs/pinyin-dogfood-2026-06-30/MODERN-FREQ-DESIGN.md
Key constraint: score ∈ [0, 25_000] — strictly less than one tier step (30k)
so corpus freq cannot cross tier boundary. v2 dict (words/chars) is the
authority of "what exists"; jieba is only used for "how to rank within tier".
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
V2_DATA = REPO / "core/crates/inputx-pinyin-v2/data"
WORDS_TSV = V2_DATA / "words.tsv"
CHARS_TSV = V2_DATA / "chars.tsv"
MODERN_VOCAB_TSV = REPO / "tools/scoring/data/polish/modern_vocab_v1.tsv"
OUTPUT_TSV = V2_DATA / "modern_freq.tsv"

SCORE_CAP = 25_000   # less than one tier step (30k) — never crosses tier

JIEBA_DICT = Path("/Users/doracawl/Library/Python/3.9/lib/python/site-packages/jieba/dict.txt")


def load_jieba_dict(path: Path) -> dict[str, int]:
    """Parse jieba dict.txt: `word freq pos\\n` → {word: freq}."""
    freq: dict[str, int] = {}
    with path.open(encoding="utf-8") as f:
        for ln in f:
            parts = ln.strip().split(" ")
            if len(parts) < 2:
                continue
            word, raw_freq = parts[0], parts[1]
            try:
                freq[word] = int(raw_freq)
            except ValueError:
                continue
    return freq


def load_v2_vocab() -> set[str]:
    """Load every word in v2 words.tsv + every char in chars.tsv."""
    vocab: set[str] = set()
    with WORDS_TSV.open(encoding="utf-8") as f:
        for ln in f:
            if not ln.strip() or ln.startswith("#"):
                continue
            parts = ln.rstrip("\n").split("\t")
            if len(parts) < 2:
                continue
            vocab.add(parts[1])  # word column
    with CHARS_TSV.open(encoding="utf-8") as f:
        for ln in f:
            if not ln.strip() or ln.startswith("#"):
                continue
            parts = ln.rstrip("\n").split("\t")
            if len(parts) < 1:
                continue
            vocab.add(parts[0])  # char column
    # Also include words added via polish overlay (modern_vocab_v1.tsv) —
    # e.g. country names, modern tech terms not in CC-CEDICT proper.
    if MODERN_VOCAB_TSV.exists():
        with MODERN_VOCAB_TSV.open(encoding="utf-8") as f:
            for ln in f:
                if not ln.strip() or ln.startswith("#"):
                    continue
                parts = ln.rstrip("\n").split("\t")
                if len(parts) < 2:
                    continue
                vocab.add(parts[1])  # word column
    return vocab


def compute_scores(jieba_freq: dict[str, int], vocab: set[str]) -> list[tuple[str, int]]:
    """Assign percentile-rank score to each vocab word.
    Words not in jieba dict → score 0 (古汉语/罕用 demote signal).
    """
    # Sort jieba by freq desc, assign rank 1..N
    sorted_words = sorted(jieba_freq.items(), key=lambda kv: -kv[1])
    N = len(sorted_words)
    rank = {w: i + 1 for i, (w, _) in enumerate(sorted_words)}

    rows: list[tuple[str, int]] = []
    for w in vocab:
        if w in rank:
            percentile = 1.0 - (rank[w] - 1) / N
            score = round(percentile * SCORE_CAP)
        else:
            score = 0
        rows.append((w, score))
    # Sort by score desc for human-readability + diff stability
    rows.sort(key=lambda kv: (-kv[1], kv[0]))
    return rows


def write_tsv(rows: list[tuple[str, int]], path: Path) -> None:
    with path.open("w", encoding="utf-8") as f:
        f.write("# modern_freq.tsv — tiebreaker score for v2 same-tier ranking\n")
        f.write("# Generated by tools/v2-ingest/build-modern-freq.py from jieba dict.txt\n")
        f.write("# Schema: <word_or_char>\\t<score>\n")
        f.write(f"# Score range: 0..{SCORE_CAP}. 0 = not in modern corpus (古汉语/罕用 signal).\n")
        f.write("# Used by v2 query as same-tier tiebreaker; never crosses tier boundary.\n")
        f.write("# Sort: score desc, word asc (diff-friendly).\n")
        for w, s in rows:
            f.write(f"{w}\t{s}\n")


def main() -> int:
    if not JIEBA_DICT.exists():
        sys.stderr.write(f"jieba dict not found at {JIEBA_DICT}\n")
        sys.stderr.write("Try: python3 -m pip install --user jieba\n")
        return 1
    jieba_freq = load_jieba_dict(JIEBA_DICT)
    vocab = load_v2_vocab()
    rows = compute_scores(jieba_freq, vocab)

    in_corpus = sum(1 for _, s in rows if s > 0)
    out_corpus = sum(1 for _, s in rows if s == 0)
    print(f"vocab size:          {len(rows):>7}")
    print(f"in jieba corpus:     {in_corpus:>7} ({100*in_corpus/len(rows):.1f}%)")
    print(f"out of corpus (0):   {out_corpus:>7} ({100*out_corpus/len(rows):.1f}%)")
    print(f"top 10 by score:")
    for w, s in rows[:10]:
        print(f"  {s:>5}  {w}")
    print(f"score 0 sample (first 5):")
    zeros = [(w, s) for w, s in rows if s == 0][:5]
    for w, s in zeros:
        print(f"  {s:>5}  {w}")

    write_tsv(rows, OUTPUT_TSV)
    print(f"wrote {OUTPUT_TSV} ({len(rows)} rows)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
