"""
Systemic sweep of wubi 繁体 chars from the encoder data sources.

Char-level entries (layer 0) are generated by the inputx-wubi build.rs
encoder running over seed.txt + auto_decomp.txt; library.tsv is only
a freq overlay on top, NOT the entry source.  To actually remove a
TRAD char from wubi, delete its row from the encoder source files.

Sweep rule:
  for each char c in auto_decomp.txt (one row per char):
    if opencc t2s(c) != c            (c is TRAD with simp counterpart)
       AND t2s(c) appears in {auto_decomp.txt chars, seed.txt chars,
                              jianma_simplified.txt chars}
                                     (simp peer reachable via wubi)
    THEN delete c's row from auto_decomp.txt.

Output:
  - audit list (char, simp_counterpart, source-where-simp-appears)
  - rewritten auto_decomp.txt with TRAD rows removed
  - library.tsv freq-override rows for the deleted chars are
    cleaned up as a follow-up (these become dead overlays)
"""
import subprocess
from pathlib import Path

ROOT = Path("core/crates/inputx-wubi/data")
AUTO = ROOT / "auto_decomp.txt"
SEED = ROOT / "seed.txt"
JIANMA = ROOT / "jianma_simplified.txt"

# Gather all chars present in each source.
def chars_in(path, col=0, sep="\t"):
    s = set()
    for line in path.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#"): continue
        parts = line.split(sep)
        if len(parts) <= col: continue
        first = parts[col]
        for ch in first:
            s.add(ch)
    return s

auto_lines = AUTO.read_text(encoding="utf-8").splitlines()
auto_chars = chars_in(AUTO)
seed_chars = chars_in(SEED)
jianma_chars = chars_in(JIANMA)
all_wubi_chars = auto_chars | seed_chars | jianma_chars
print(f"chars in auto_decomp.txt    : {len(auto_chars)}")
print(f"chars in seed.txt           : {len(seed_chars)}")
print(f"chars in jianma_simplified  : {len(jianma_chars)}")
print(f"union                       : {len(all_wubi_chars)}")

# t2s mapping per char
chars = sorted(all_wubi_chars)
proc = subprocess.run(
    ["opencc", "-c", "t2s.json"],
    input="\n".join(chars),
    capture_output=True, text=True
)
simp_chars = proc.stdout.rstrip("\n").split("\n")
simp_map = {c: s for c, s in zip(chars, simp_chars)}

# Identify TRAD chars in auto_decomp.txt whose simp peer is in any wubi source
def simp_present_in_wubi(simp):
    # simp char(s) must be reachable via some wubi source
    return all(ch in all_wubi_chars for ch in simp)

# Iterate auto_decomp.txt rows
deletes = []     # (char, simp_peer)
orphans = []     # TRAD whose simp peer is NOT in any wubi source
kept_rows = []
for line in auto_lines:
    if not line or line.startswith("#"):
        kept_rows.append(line); continue
    parts = line.split("\t")
    if not parts:
        kept_rows.append(line); continue
    ch = parts[0]
    if len(ch) != 1:
        kept_rows.append(line); continue
    simp = simp_map.get(ch, ch)
    if simp == ch:
        kept_rows.append(line); continue
    # TRAD char
    if simp_present_in_wubi(simp):
        deletes.append((ch, simp))
        # skip line (delete)
    else:
        orphans.append((ch, simp))
        kept_rows.append(line)

print(f"\nTRAD rows in auto_decomp.txt:")
print(f"  deleted (simp peer reachable) : {len(deletes)}")
print(f"  kept (orphan TRAD)            : {len(orphans)}")

# Rewrite auto_decomp.txt
AUTO.write_text("\n".join(kept_rows) + "\n", encoding="utf-8")
print(f"\nauto_decomp.txt rows: {len(auto_lines)} → {len(kept_rows)} (-{len(auto_lines)-len(kept_rows)})")

# Audit dumps
Path("/tmp/wubi_trad_deleted_v2.tsv").write_text(
    "# trad\tsimp_peer\n" + "\n".join(f"{c}\t{s}" for c,s in deletes) + "\n",
    encoding="utf-8"
)
Path("/tmp/wubi_trad_orphans_v2.tsv").write_text(
    "# trad\tsimp_form\n" + "\n".join(f"{c}\t{s}" for c,s in orphans) + "\n",
    encoding="utf-8"
)
print("audit: /tmp/wubi_trad_deleted_v2.tsv  /tmp/wubi_trad_orphans_v2.tsv")
